steps:
  # 1. Construir la imagen Docker desde la raíz
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-react', '.']

  # 2. Subir la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend-react']

  # 3. Desplegar en Cloud Run usando el puerto 8080
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'frontend-react-service'
      - '--image=gcr.io/$PROJECT_ID/frontend-react'
      - '--region=us-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'

images:
  - 'gcr.io/$PROJECT_ID/frontend-react'