steps:
  # 1. Construir la imagen Docker para el Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend-react', './frontend']

  # 2. Subir la imagen al Container Registry de Google Cloud
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend-react']

  # 3. Desplegar en Google Cloud Run en la región us-south1 (Dallas)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'frontend-react-service'
      - '--image=gcr.io/$PROJECT_ID/frontend-react'
      - '--region=us-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=80'

images:
  - 'gcr.io/$PROJECT_ID/frontend-react'